version: "3.8"

services:
  app:
    container_name: collect-am-api_main-service_dev
    build:
      context: ./main-service
      dockerfile: Dockerfile.dev
    image: collect_am-api-dev:v1.0
    ports:
      - "8085:8085"
    env_file:
      - ./.env
    environment:
      - GO_ENV=${GO_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL=${DB_SSL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./main-service:/app
      - ./main-service/.air.toml:/app/.air.toml
    networks:
      - app-network
    working_dir: /app

networks:
  app-network:
    driver: bridge
