version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.staging
    image: collect_am-api:v1.0
    ports:
      - "8085:8085"
    environment:
      - GO_ENV=${GO_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL=${DB_SSL}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - ./.env
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
