# Use the official Golang image
FROM golang:1.22-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

RUN go install github.com/cosmtrek/air@v1.40.4

COPY cmd/ ./cmd/

FROM alpine:latest  
RUN apk add --no-cache go
WORKDIR /app

COPY --from=builder /go/bin/air /usr/local/bin/air

EXPOSE 8085

CMD ["air", "-c", ".air.toml"]
